info:
  contact: {}
paths:
  /test:
    post:
      consumes:
      - multipart/form-data
      description: Register user with individual form fields
      parameters:
      - description: Name
        example: '"Ali"'
        in: formData
        name: name
        required: true
        type: string
      - description: Surname
        example: '"Valiyev"'
        in: formData
        name: surname
        required: true
        type: string
      - description: Email
        example: '"ali@example.com"'
        in: formData
        name: email
        required: true
        type: string
      - description: Birth Date
        example: '"1999-01-01"'
        in: formData
        name: birth_date
        required: true
        type: string
      - description: Gender
        enum:
        - male
        - female
        in: formData
        name: gender
        required: true
        type: string
      - description: Password
        example: '"password123"'
        in: formData
        name: password
        required: true
        type: string
      - description: Phone Number
        example: '"+998901234567"'
        in: formData
        name: phone_number
        required: true
        type: string
      - description: Address
        example: '"Tashkent"'
        in: formData
        name: address
        required: true
        type: string
      - description: Role
        enum:
        - admin
        - user
        in: formData
        name: role
        required: true
        type: string
      - description: Provider
        enum:
        - google
        - any
        in: formData
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Register user
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    description: API Gateway
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
